LivrariaIGE/urls.py
# Importação da interface de administração fornecida pelo Django
from django.contrib import admin
# Importação da funções para criar rotas de URL
from django.urls import path, include, re_path
# Importações para configurar a exibição de estáticos e de mídia
from django.conf import settings
from django.conf.urls.static import static

# Lista onde as URLs e suas visualizações são associadas
urlpatterns = [
    path("admin/", admin.site.urls),
    re_path('', include('apps.autor.urls')),
    re_path('', include('apps.livros.urls')),
    re_path('', include('apps.usuario.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/autor/urls.py
# Importação de uma função Django que associa URL'S
from django.urls import path
# Importação da classe 'DetalhesAutorView'
from apps.autor.views import DetalhesAutorView

app_name = 'autor'

# Definição da URL para o app 'autor'
urlpatterns = [
    path('autor/<slug:slug>', DetalhesAutorView.as_view(), name='detalhes_autor'),
]

apps/livros/urls.py
# Importação de uma função Django que associa URL'S
from django.urls import path
# Importação das classes de interesse ao livro
from apps.livros.views import (
    ListarLivrosView,
    AdicionarLivroView,
    DetalhesLivroView,
    AlternarFavoritosView,
)

app_name = 'livros'

# Definição da URL para o app 'livros'
urlpatterns = [
    path('livros/', ListarLivrosView.as_view(), name='lista_livros'),
    path('livros/<slug:slug>', DetalhesLivroView.as_view(), name='detalhes_livro'),
    path('livros/adicionar/', AdicionarLivroView.as_view(), name='novo_livro'),
    path('livro/<int:pk>/favoritar/', AlternarFavoritosView.as_view(), name='alternar_favorito'),
]

apps/usuario/urls.py
# Importação de uma função Django que associa URL'S
from django.urls import path
# Importação de uma view do Djando para permitir o logout
from django.contrib.auth.views import LogoutView
# Importação das classes de interesse ao usuario
from apps.usuario.views import (
    HomePage, 
    RegistrarUsuarioView, 
    PerfilUsuarioView,
)

app_name = 'usuario'

 # Definição da URL para o app 'usuario'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('login/', RegistrarUsuarioView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='usuario:home'), name='logout'),
    path('perfil/<username>', PerfilUsuarioView.as_view(), name='perfil'),
]

apps/autor/models.py
# Importação da biblioteca para gerar id 
import uuid
# Importação da classe de configuração do modelo
from django.db import models
# Importação da função que transforma textos em slugs
from django.utils.text import slugify

# Definição da classe 'Autor' que herda de uma classe padrão do Django
class Autor(models.Model):
    # Todos os atributos que constaram na classe
    nome_completo = models.CharField(max_length=100) # Tipo campo de texto
    biografia = models.TextField(max_length=500, blank=True) # Tipo campo de texto longo, é opcional
    data_nascimento = models.DateField( # Tipo data
        blank=True, # É opcional 
        null=True, # Pode ser nulo
        verbose_name='Data de nascimento', # Nome que aparecerá na tela admin
    )
    slug = models.SlugField(unique=True, blank=True) # Tipo slug, é único e opcional
    foto_perfil = models.ImageField( # Tipo imagem 
        upload_to='autor', # Imagens armazenadas na pasta 'autor'
        null=True, # Pode ser nula
        blank=True, # É opcional
        default='usuario.png' # Imagem padrão para caso de não upload
    )

    # Configuração de informações adicionais
    class Meta:
        db_table  = 'autor' # Nome da tabela no BD
        # Nomes que aparecerão na tela admin
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'
    
    # Como autor será listado na tela admin
    def __str__(self):
        return self.nome_completo
    
    # Definição de comportamento ao salvar um objeto 
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.nome_completo) # Cria um slug com base no nome através da função slugify
            slug = base_slug

            while Autor.objects.filter(slug=slug).exists(): # Verifica se o slug já existe no BD
                slug = f"{base_slug}-{uuid.uuid4().hex[:8]}"  # Gera um ID único de 8-dígitos

            self.slug = slug
        
        super().save(*args, **kwargs) # Salva o objeto no BD

apps/usuario/models.py
from django.core.exceptions import ValidationError
# Importação da classe de configuração do modelo
from django.db import models
from django.contrib.auth.models import User
# Importação de classes associadas
from apps.usuario.choices import (
    Generos,
    Ocupacoes,
    Identificacoes,
)

# Validação do campo de identificação (numérico, 11 a 13 digitos)
def validar_identificacao(valor, tipo):
    if not valor.isdigit():  # Garante que seja um valor numerico
        raise ValidationError("Identificação deve ser um valor numérico.")
    
    comprimento = len(valor)

    if tipo == 'C' and comprimento != 11: # Validação CPF
        raise ValidationError("CPF deve ter 11 dígitos.")
    elif tipo == 'M' and comprimento != 13: # Validação matrícula
        raise ValidationError("Matrícula deve ter 13 dígitos.")

# Definição da classe 'Usuario' que herda de uma classe padrão do Django
class Usuario(User):
    ocupacao = models.CharField( # Tipo campo livre
        verbose_name='Ocupação',
        max_length=1,
        choices=Ocupacoes.choices, # Restringe a seleção
        null=False, # Não pode ser nulo
        blank=False, # Não é opcional
    )
    data_nascimento = models.DateField(
        null=True, # Pode ser nulo
        blank=True, # É opcional
        verbose_name="Data de nascimento",
    )
    tipo_identificacao = models.CharField(
        max_length=1,
        choices=Identificacoes.choices,
        default='C',
    )
    identificacao = models.CharField(
        max_length=13,
        unique=True,
        null=False,
        blank=True,
    )
    genero = models.CharField(
        verbose_name="gênero",
        max_length=1,
        choices=Generos.choices,
        blank=False,
        null=False,
    )
    foto_perfil = models.ImageField(
        upload_to='usuario',
        null=True,
        default='usuario.png',
    )

    @property
    def nome_completo(self):
        return f"{self.first_name} {self.last_name}".strip()
    
    # Validação personalizada para o campo identificação
    def clean(self):
        super().clean()
        validar_identificacao(self.identificacao, self.tipo_identificacao)

    # Configuração de informações adicionais
    class Meta:
        db_table  = 'usuario'

class Favoritos(models.Model):
    from apps.livros.models import Livros
    # Todos os atributos que constaram na classe (composição)
    livro = models.ForeignKey(
        Livros,
        related_name='livro_favorito',
        on_delete=models.CASCADE,
    )
    usuario = models.ForeignKey(
        Usuario,
        related_name='favoritos_usuario',
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('livro', 'usuario')
        verbose_name = 'Livro Favorito'
        verbose_name_plural = 'Livros Favoritos'

    # Como livro será listado na tela admin
    def __str__(self):
        return self.livro.titulo

apps/autor/views.py
# Importação de uma classe do Django que exibe detalhes
from django.views.generic import (
    DetailView,
)
# Importação da classe 'Autor' e seu app
from apps.autor.models import Autor

# Criação da classe 'DetalhesAutorView' que faz a chamada do modelo e da tela correspondente a ela
class DetalhesAutorView(DetailView):
    model = Autor
    template_name = 'autor.html'

apps/livros/views.py
# Importação des bibliotecas de restrições de acessos
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Importação de uma biblioteca de paginação
from django.core.paginator import Paginator
from django.db.models import Case, When, Value, IntegerField, Q
from django.http import HttpResponseForbidden, JsonResponse
# Importação da função que exibe erro 404
from django.shortcuts import get_object_or_404, redirect
# Importação da função que gera URL'S dinamicamente
from django.urls import reverse_lazy, reverse
# Importação de classes para construir view
from django.views.generic import (
    CreateView,
    DetailView,
    ListView, 
    View,
)
# Importação de formulários relacionados ao livro
from apps.livros.forms import (
    AdicionarLivrosForm,
    ComentarLivroForm,
)
# Importação de classes de associação
from apps.livros.models import Livros, Comentario, Link
from apps.usuario.models import Favoritos

# Criação da classe 'ListarLivrosView' 
class ListarLivrosView(ListView):
    model = Livros # Faz a chamada do modelo que a corresponde
    template_name = 'search.html' # Faz a chamada da tela que a corresponde
    context_object_name = 'livros' # Nome da variável de acesso ao conjunto
    paginate_by = 10 # Quantidade de respostas na tela
 
    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search_query', '').strip()
        ano_publicacao = self.request.GET.get('ano_publicacao', '').strip()
        editora = self.request.GET.get('editora', '').strip()
        materia = self.request.GET.get('materia', '').strip()
        curso = self.request.GET.get('curso', '').strip()
        periodo = self.request.GET.get('periodo', '').strip()

        # # Caso haja um termo de busca a função apply é chamada
        if search_query:
            queryset = self.apply_search_query(queryset, search_query)

        # Insere filtros adicionais por atributos
        queryset = self.apply_filters(queryset)

        # Apply filters
        if ano_publicacao:
            queryset = queryset.filter(ano_publicacao=ano_publicacao)
        if editora:
            queryset = queryset.filter(editora__nome__icontains=editora)
        if materia:
            queryset = queryset.filter(materia__nome__icontains=materia)
        if curso:
            queryset = queryset.filter(materia__cursos__nome__icontains=curso)  # Traverse through Materias to Cursos
        if periodo:
            queryset = queryset.filter(materia__periodo=periodo)  # Filter by periodo in Materias
        
        # Previnir resultados repetidos
        queryset = queryset.distinct()

        return queryset

    def apply_search_query(self, queryset, search_query):
        # Definição de atributos de busca
        return queryset.filter(
            Q(titulo__icontains=search_query) |
            Q(autor__nome_completo__icontains=search_query)
        )

    def apply_filters(self, queryset):
        filters = {}

        # Filtro por ano
        ano_publicacao = self.request.GET.get('ano_publicacao')
        if ano_publicacao:
            filters['ano_publicacao'] = ano_publicacao

        # Filtro por editora
        editora = self.request.GET.get('editora')
        if editora:
            filters['editora__nome__icontains'] = editora

        # Filtro por matéria
        materia = self.request.GET.get('materia')
        if materia:
            filters['materia__nome__icontains'] = materia
        
        # Filtro por período
        periodo = self.request.GET.get('periodo')
        if periodo:
            # Acessando curso através de materia
            filters['materia__periodo'] = periodo

        # Filtro por curso
        curso = self.request.GET.get('curso')
        if curso:
            # Acessando curso através de materia
            filters['materia__cursos__nome__icontains'] = curso

        return queryset.filter(**filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('search_query', '')
        context['ano_publicacao'] = self.request.GET.get('ano_publicacao', '')
        context['editora'] = self.request.GET.get('editora', '')
        context['materia'] = self.request.GET.get('materia', '')
        context['periodo'] = self.request.GET.get('periodo', '')
        context['curso'] = self.request.GET.get('curso', '')
        return context

class AdicionarLivroView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Livros
    form_class = AdicionarLivrosForm
    template_name = 'adicionarLivro.html'
    login_url = 'usuario:login'
    success_url = '.'

    def form_valid(self, form):
        # Salva o livro adicionado
        self.object = form.save()

        # Process new links
        new_links = form.cleaned_data.get('new_links', '').strip()
        if new_links:
            for line in new_links.split('\n'):
                if line.strip():
                    site, link = line.strip().split(',', 1)
                    link_obj, created = Link.objects.get_or_create(site=site.strip(), link=link.strip())
                    self.object.links.add(link_obj)

        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return super().form_invalid(form)

    def test_func(self):
        # Permite acesso se o usuário for superuser ou estiver no grupo 'professor'
        user = self.request.user
        return user.is_superuser or user.groups.filter(name='professor').exists()

    def get_redirect_url(self):
        # Se não for professor, redireciona para outra pagina
        if not self.test_func():
            return 'usuario:home'
        return super().get_redirect_url()


class DetalhesLivroView(DetailView):
    model = Livros
    template_name = 'livro.html'
    context_object_name = 'livro'
    login_url = 'usuario:login'
    sucess_url = '.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ComentarLivroForm()  # Form para comentarios
        
        livro = self.get_object()
        comentarios_list = Comentario.objects.filter(livro=livro).annotate(
        tipo_ordem=Case(
            When(usuario__tipo_identificacao='P', then=Value(1)),  # Professores primeiro
            When(usuario__tipo_identificacao='E', then=Value(2)),  # Estudantes depois
            default=Value(3),
            output_field=IntegerField()
        )
        ).order_by('tipo_ordem', '-postado_em')

        # Paginação
        paginator = Paginator(comentarios_list, 5)  # Define 5 comentários por página
        page = self.request.GET.get('page')
        comentarios = paginator.get_page(page)

        context['comentarios'] = comentarios

        if self.request.user.is_authenticated and hasattr(self.request.user, 'usuario'):
            context['is_favorited'] = Favoritos.objects.filter(livro=livro, usuario=self.request.user.usuario).exists()
        else:
            context['is_favorited'] = False

        return context
    
    def get_object(self):
        slug = self.kwargs['slug']
        return get_object_or_404(Livros, slug=slug)

    def post(self, request, *args, **kwargs):
        if self.request.user.is_superuser:
            # Se o usuário é um administrador, não terá permissão para comentar no livro
            return HttpResponseForbidden("Você não tem permissão para comentar.")

        livro = self.get_object()
        
        comentario_id = request.POST.get("comentario_id")
        if comentario_id:
            return self.excluir_comentario(request, comentario_id)

        if request.user.is_authenticated:
            form = ComentarLivroForm(request.POST)
            
            if form.is_valid():
                comentario = form.save(commit=False)
                comentario.usuario = request.user.usuario  # Atribui o usuario atual
                comentario.livro = livro  # Atribui o livro atual
                comentario.save()
                return redirect(request.path)  # Recarrega a página após a postagem
        else:
            # Se o usuario não estiver logado, encaminha para a tela de login
            return redirect(f'{reverse("usuario:login")}?next={request.path}')

        context = self.get_context_data(**kwargs)
        context['form'] = form
        return self.render_to_response(context)
    
    def excluir_comentario(self, request, comentario_id):
        comentario = get_object_or_404(Comentario, id=comentario_id)

        # Verifica se o usuário tem permissão para excluir o comentário
        if request.user.usuario != comentario.usuario:
            return HttpResponseForbidden("Você não tem permissão para excluir este comentário.")

        comentario.delete()
        return redirect(request.path)


class AlternarFavoritosView(LoginRequiredMixin, View):
    login_url = reverse_lazy('usuario:login')

    def post(self, request, *args, **kwargs):
        if not hasattr(request.user, 'usuario'):
            # Se o usuário é um administrador, não terá permissão para favoritar o livro
            return HttpResponseForbidden("Você não tem permissão para favoritar este livro.")

        usuario = request.user.usuario
        livro = get_object_or_404(Livros, id=self.kwargs['pk'])

        # Retorna ou cria uma instância de favorito
        favorito, created = Favoritos.objects.get_or_create(usuario=usuario, livro=livro)
        
        if not created:  
            # Se já existir, desfavorita
            favorito.delete()

        # Redireciona de volta à pagina de detalhes do livro
        return redirect(reverse('livros:detalhes_livro', kwargs={'slug': livro.slug}))

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

<!-- Esse código é um template base para um projeto Django, 
 aqui está definido a estrutura principal da página para que 
 outras páginas herdem esse layout e insiram seu próprio conteúdo nos blocos definidos. -->

<head>
  
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="Cache-Control" content="no-cache" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Importação do CDN font-awesome para icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <!-- Importação de um estilo base para as páginas -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <!-- Bloco de título dinâmico para que cada página defina o seu -->
  <title>{% block title %}{% endblock %}</title>
  <!-- Bloco extra na head para as páginas adicionarem mais elementos -->
  {% block head %}{% endblock head %}
</head>

<body>
  <!-- Bloco principal onde cada página vai preencher seu conteúdo  -->
  {% block content %}{% endblock %}
</body>

</html>

templates/header.html
<html>
{% load static %}
{% block head %}
<!-- Importação do CDN de icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
    integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'css/header.css' %}">
{% endblock head %}

<body>
    <header>
        <!-- Logo com redirecionamento para a tela principal -->
        <a style="text-decoration: none;" href="{% url 'usuario:home' %}">
            <div class="logo">
                <img src="{% static 'imgs/logo.png' %}" alt="Logo">
                LivrariaIGE
            </div>
        </a>
        <!-- Barra para realizar pesquisas por atributos -->
        <form class="search-bar" action="{% url 'livros:lista_livros' %}" method="GET"
            onsubmit="return checkSearchQuery()">
            <input type="text" name="search_query" placeholder="Pesquisar..." value="{{ request.GET.search_query }}">
            <button type="submit-search">
                <!-- Icon do CDN -->
                <i class="fas fa-search"></i>
            </button>
        </form>
        <!-- Botão de adicionar livros (aparecerá apenas para professores) -->
        <div class="user-area">
            {% if request.user.usuario.ocupacao == 'P' %}
            <form action="{% url 'livros:novo_livro' %}" method="post">
                {% csrf_token %}
                <button id="add-btn" type="submit">Adicionar Livro</button>
            </form>
            {% endif %}
            <!-- Botão de fazer logout (aparecerá para quem está logado)-->
            {% if request.user.is_authenticated %}
            <form action="{% url 'usuario:logout' %}" method="post">
                {% csrf_token %}
                <button id="logout-btn" type="submit">Logout</button>
            </form>
            <!-- Botão de ver dados cadastrais com redirecionamento para a página do perfil (aparecerá para quem está logado)-->
            <a href="{% url 'usuario:perfil' request.user.username %}">
                <i class="fa-solid fa-user user-icon" id="user-icon"></i>
            </a>
            {% else %}
            <!-- Botão de fazer login (aparecerá para quem NÃO está logado)-->
            <a href="{% url 'usuario:login' %}">
                <button id="login-btn">Login</button>
            </a>
            {% endif %}
        </div>
    </header>
    <!-- Importação das configurações de aparição dos botões -->
    <script src="{% static 'js/header.js' %}"></script>
</body>

</html>

templates/livro.html
<!-- Herda as configurações da base -->
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ livro.titulo }}{% endblock title %}

{% block head %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/livro.css">
{% endblock head %}


{% block content %} 
    <!-- Importação da header -->
    {% include 'header.html' %}
    <div class="breadcrumb">
        Livros &gt; {{ livro.titulo }}
    </div>

    <!-- Seção de detalhes sobre o livro -->
    <section class="container">
        <div class="detalhes-container">
            <div class="imagem-container">
                {% if livro.capa %}
                    <img src="{{ livro.capa.url }}" alt="Capa do Livro">
                {% else %}
                    <img src="{% static 'imgs/capa_base.png' %}">
                {% endif %}
            </div>
            <div class="conteudo-container">
                <div class="titulo-estrela">
                <h2 class="livro-materia">{{ livro.titulo }}</h2>
                    <form method="post" action="{% url 'livros:alternar_favorito' livro.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="favorite_action" value="true">
                        <button id="estrela-favorito" class="estrela-favorito{% if livro in usuario.favoritos.all %}-preenchida{% else %}-vazia{% endif %}" 
                        data-livro-id="{{ livro.id }}">
                        {% if is_favorited %}
                            &#9733;  <!--  Estrela preenchida -->
                        {% else %}
                            &#9734;  <!-- Estrela vazia -->
                        {% endif %}
                        </button>
                    </form>
                </div>
                <p class="livro-editora"><strong>Editora: </strong>{{ livro.editora }}</p>
                <p class="livro-ano"><strong>Data de Publicação: </strong>{{ livro.ano_publicacao }}</p>
                <p class="livro-autor"><strong>Autor: </strong><a href="{% url 'autor:detalhes_autor' livro.autor.slug %}">{{ livro.autor.nome_completo }}</a></p>
                <p class="livro-descricao"><strong>{{ livro.descricao }}</strong></p>
            </div>
        </div>
        <a class="btn-comprar" 
            href="{% if livro.links.first %}{{ livro.links.first.link }}{% else %}#{% endif %}" 
            target="_blank">
            Comprar
        </a>
        <div id="customModal{{ livro.id }}" class="custom-modal">
            <div class="custom-modal-content">
                <span class="custom-close" onclick="closeModal('{{ livro.id }}')">&times;</span>
                <h2>Onde Comprar - {{ livro.titulo }}</h2>
                <ul id="modalLinks{{ livro.id }}">
                    {% for link in livro.links.all %}
                        <li><a href="{{ link.link }}" target="_blank">{{ link.site }}</a></li>
                    {% empty %}
                        <li>Não há links disponíveis para este livro.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>

    <!-- Seção de comentários sobre o livro -->
    <div class="comentarios-container">
        <h3 class="comentarios-titulo">Comentários</h3>
        
        {% if comentarios %}
            {% for comentario in comentarios %}
                <div class="comentario">
                    <div class="comentario-header">
                        <div class="comentario-avatar">
                            {% if usario.foto_perfil %}
                            <img src="{{ usuario.foto_perfil.url }}" alt="Foto de {{ username }}">
                            {% else %}
                            <img src="{% static 'imgs/usuario.png' %}">
                            {% endif %}
                        </div>
                        <span class="comentario-usuario">{{ comentario.usuario.get_full_name }} &gt; </span> {{ comentario.postado_em }}<br>
                    </div>
                    <p class="comentario-texto">{{comentario.corpo}}</p>
                    {% if request.user.usuario == comentario.usuario or request.user.is_superuser %}
                        <form method="POST" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="comentario_id" value="{{ comentario.id }}">
                            <button type="submit" class="btn-excluir" onclick="return confirm('Tem certeza que deseja excluir este comentário?');">
                                Excluir
                            </button>
                        </form>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="paginacao">
                {% if comentarios.has_previous %}
                    <a href="?page=1" class="pagina-link">Primeira</a>
                    <a href="?page={{ comentarios.previous_page_number }}" class="pagina-link">Anterior</a>
                {% endif %}

                <span class="pagina-atual">Página {{ comentarios.number }} de {{ comentarios.paginator.num_pages }}</span>

                {% if comentarios.has_next %}
                    <a href="?page={{ comentarios.next_page_number }}" class="pagina-link">Próxima</a>
                    <a href="?page={{ comentarios.paginator.num_pages }}" class="pagina-link">Última</a>
                {% endif %}
            </div>
        {% endif %}
        
        <!-- Área de realizar novos comentários -->
        <div class="novo-comentario">
            <h3 class="comentarios-titulo">Novo comentário: </h3>
            <form method="POST" data-authenticated="{% if request.user.is_authenticated %}true{% else %}false{% endif %}"> {% csrf_token %}
              {% for field in form %}
                <div>
                    {{ form.corpo }}
                  {% if field.errors %}
                    <div style="color: red;">
                      {{ field.errors }}
                    </div>
                  {% endif %}
                </div>
              {% endfor %}
              <button class="btn-enviar" type="submit">Enviar Comentário</button>
            </form>
        </div>
    </div>

    <!-- Janela que impede o usuário não autenticado de comentar e redireciona para o login -->
    <div id="login-popup" class="popup">
        <div class="popup-content">
            <span class="close-popup">&times;</span>
            <p>Você precisa estar logado para comentar.</p>
            <a href="{% url 'usuario:login' %}?next={{ request.path }}">Clique aqui para fazer login</a>.
        </div>
    </div>
    <script src="{% static 'js/livros.js' %}"></script>
    {% include 'footer.html' %}
{% endblock content %}
</html>

templates/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ username }}{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/perfil.css' %}">
{% endblock head %}


{% block content %}
  {% include 'header.html' %}
    <div class="container">
      <div class="usuario-imagem">
        {% if usario.foto_perfil %}
          <img src="{{ usuario.foto_perfil.url }}" alt="Foto de {{ username }}">
        {% else %}
          <img src="{% static 'imgs/usuario.png' %}">
        {% endif %}
      </div>
      <div class="conteudo-container">
        <div class="usuario-header">
          <span class="usuario">{{ username }}</span>
        </div>
        <p>{{ usuario.nome_completo }}</p>
        <p>{{ usuario.data_nascimento }}</p>
        <p>{{ usuario.get_genero_display }}</p>
        <p>{{ usuario.get_ocupacao_display }}</p>
      </div>
      <div class="favoritos">
      <div class="favoritos-header">
        <h2>Favoritos do usuário</h2>
      </div>
      <div class="livros-grid">
        {% for favorito in favoritos %}
        <a href="{% url 'livros:detalhes_livro' favorito.livro.slug %}" class="livro-item">
          {% if favorito.livro.capa %}
            <img src="{{ favorito.livro.capa.url }}" alt="{{ favorito.livro.titulo }}" class="livro-capa">
          {% else %}
            <img src="{% static 'imgs/capa_base.png' %}">
          {% endif %}
          <h3>{{ favorito.livro.titulo }}</h3>
        </a>
        {% endfor %}
      </div>
    </div>

  <script src="{% static 'perfil.js' %}"></script>

{% endblock content %}